import Head from "next/head";
import { produtos } from "../Dados/dados-produtos.js";
import BotaoCategoria from "../Componentes/Categorias/buttonCategoria.js";
import styles from "../styles/Home.module.css";

export default function Home() {
  return(
    <>
      <Head>
        <title>Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/** Google fontes*/}
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Poppins&display=swap" rel="stylesheet"></link>
      </Head>
      <main className={styles.main}>
        <section className={styles.banner}>
          {/*Imagem de fundo*/}
          <h1>Restaurant</h1>
          <p>De pratos clássicos a criações surpreendentes, nosso cardápio é um requinte de sabores refinados</p>
        </section>
        {/**Fim do banner */}
        <section className={styles.conteudo}>
            <BotaoCategoria />
        </section>
      </main>
    </>
  );
}